### ISSUE TITLE
What is the reasoning behind having a timeout?

### ISSUE THREAD

**Issue by Keagel** [vh13294/crytomator-docker#1]
Is it simply because you don't want your vault to be indefinitely mounted or have you found that having it mounted for too long is an issue?

**Comment by vh13294** [comment]
I have updated the README.

timeout can be disabled by input 0.

TIMEOUT: 0 (disable timeout and server will run indefinitely)

**Comment by vh13294** [comment]
To answer your question! 

I am accessing my data via share server. 
I only need my data occasionally, and don’t want to expose the service to other users for too long.

**Comment by Keagel** [comment]
> timeout can be disabled by input 0.
> 
> TIMEOUT: 0 (disable timeout and server will run indefinitely)

That's what I did after looking at the Dockerfile and reading the doc for `timeout` so no worries!

> To answer your question!
> 
> I am accessing my data via share server.
> I only need my data occasionally, and don’t want to expose the service to other users for too long.

I see. I thought it had something to do with a Cryptomator limitation. Thank you for the answer!
